language: python
cache: pip
sudo: false
python:
 - "3.6"
install: pip install \
  codacy-coverage \
  coverage flake8 \
  flake8-docstrings \
  flake8-per-file-ignores \
  flake8-quotes \
  tox-travis
before_script:
  - coverage erase
script:
  - flake8
  - tox
after_success:
  - coverage combine
  - coverage report
  - coverage xml -o coverage/xml/coverage.xml
  - coverage html --directory=coverage/html
  - python-codacy-coverage -r coverage/xml/coverage.xml
