language: python
cache: pip
sudo: false
python:
 - "3.6"

# pydocstyle pinned due to build error (used by flake8-docstrings). See:
# - https://gitlab.com/pycqa/flake8-docstrings/issues/36
# - https://github.com/PyCQA/pydocstyle/issues/375
install: pip install \
  codacy-coverage \
  coverage \
  flake8 \
  flake8-docstrings \
  flake8-per-file-ignores \
  flake8-quotes \
  "pydocstyle<4.0.0"
  tox-travis
before_script:
  - coverage erase
script:
  - flake8
  - tox
after_success:
  - coverage combine
  - coverage report
  - coverage xml -o coverage/xml/coverage.xml
  - coverage html --directory=coverage/html
  - python-codacy-coverage -r coverage/xml/coverage.xml
